version: "3"
services:
  backend:
    build: ./backend
    command: ["/app/backend/scripts/run.sh"]
    volumes:
      - static_volume:/app/backend
    environment:
      ADMIN_PASSWORD: "password"
      ADMIN_USERNAME: "admin"
      DATABASE_URL: "mysql+pymysql://sat@sat@localhost/sat"
      DEBUG: "False"
      FLASK_APP: "app.py"
      FLASK_DEBUG: 0
      SECRET_KEY: "randomkeygoeshere"
    depends_on:
      - mysql
    networks:
      - backend-network
      - frontend-network

  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - www:/app/dist

  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - www:/var/www/html:ro
  #     - static_volume:/static
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend
  #   networks:
  #     - network-frontend

  mysql:
    image: mysql:5.7.29
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "sat"
      MYSQL_PASSWORD: "sat"
      MYSQL_DATABASE: "sat"
    networks:
      - backend-network

volumes:
  mysql_data:
  static_volume:
  www:

networks:
  backend-network:
  frontend-network:
