version: "3.7"
services:
  backend:
    image: python:3.7
    command: ["/app/backend/scripts/run-dev.sh"]
    volumes:
      - ./backend:/app/backend
      - ./backend/venv:/app/backend/venv
      - backend_data:/root/uploads
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "password"
      DATABASE_URL: "mysql+pymysql://sat:sat@mysql/sat?charset=utf8mb4"
      UPLOAD_FOLDER: "/root/uploads"
      FLASK_APP: "app.py"
      FLASK_DEBUG: 1
      FLASK_ENV: "development"
      SECRET_KEY: "randomkeygoeshere"
      JWT_SECRET_KEY: "secretkey"
      JWT_REDIS_STORE_URL: "redis://:sat@redis:6379/0"
    ports:
      - 5000:5000
    depends_on:
      - mysql
      - redis
    networks:
      - backend-network
      - frontend-network

  frontend:
    image: node:13.13.0
    command: ["/app/frontend/scripts/run-dev.sh"]
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/node_modules:/app/frontend/node_modules
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - frontend-network

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/mysql
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "sat"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "sat"
      MYSQL_PASSWORD: "sat"
    command: --init-file=/mysql/create_database.sql --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    networks:
      - backend-network

  redis:
    build: ./redis
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: "sat"
    ports:
      - 6379:6379
    networks:
      - backend-network

volumes:
  mysql_data:
  redis_data:
  backend_data:

networks:
  backend-network:
  frontend-network:
